Support "size" and "timeout" on *_fuzz_test
bazelbuild/rules_fuzzing pull request #204
Opened 2022-05-12 08:31 UTC by fmeum

Fixes #202

2022-05-12 08:36 UTC, fmeum commented
@stefanbucur The CI failure is fixed by #205. I rebased this PR onto it.

2022-05-12 20:26 UTC, stefanbucur requested changes
Great, thank you!

2022-06-05 08:03 UTC, fmeum commented on fuzzing/private/fuzz_test.bzl
> +        timeout: The timeout for the fuzzing regression test.
Added a link and a clarified the distinction between "fuzzing" and "regression test". Do you think this is clear enough now?

2022-06-19 21:06 UTC, stefanbucur commented on fuzzing/private/fuzz_test.bzl
> +        timeout: The timeout for the fuzzing regression test.
Looks great!

2022-06-19 21:06 UTC, stefanbucur approved these changes
Apologies for the delay!

2022-06-19 21:06 UTC, merged