Add coverage support to regression tests
bazelbuild/rules_fuzzing pull request #212
Opened 2022-09-28 09:59 UTC by fmeum

Co-authored-by: Zhen Yu Ding <zhendeveloper@gmail.com>

2022-09-28 10:16 UTC, fmeum commented
@stefanbucur Could you review this? This differs from #174 in that the LCOV merge is no longer build without `bazel coverage`.

@zhenyudg I added you as a coauthor.

2022-11-10 16:05 UTC, fmeum commented
@stefanbucur Friendly ping

2022-11-10 16:11 UTC, stefanbucur commented
Thanks so much for the ping, it totally fell through the cracks. I'll take a look by EOD.

(PS: Please feel free to ping me if you don't get an answer within a few days. Nowadays I'm spending less time on Github so things may easily slip off my attention.)

2022-11-11 16:49 UTC, stefanbucur requested changes
This is great - thanks so much for figuring out a way to do this cleanly. Just small-ish comments / suggestions.

2022-11-13 00:08 UTC, fmeum commented on fuzzing/tools/noop_lcov_merger.sh
> +#!/usr/bin/env sh
Added a comment.

2022-11-13 00:08 UTC, fmeum commented on fuzzing/tools/BUILD
> +    name = "collect_code_coverage",
Done

2022-11-14 17:50 UTC, stefanbucur approved these changes
LGTM, but we seem to have new test failures?

2022-11-14 18:26 UTC, fmeum commented
> LGTM, but we seem to have new test failures?

Looks like Bazel CI replaced `python` with `python3`, which is incompatible with Bazel 4. I will try raising the minimum version and see whether that fixes the failure.

2022-11-15 03:17 UTC, fmeum commented
@stefanbucur I updated the Bazel version to 5.0.0, which makes Bazel look for `python3` in `PATH`. The [CI run still fails](https://github.com/bazelbuild/rules_fuzzing/actions/runs/3467075874/jobs/5791585426#step:4:239), but I when I run `/usr/bin/env python3` in `base-builder` locally, that passes. Not sure what's wrong here.

2022-11-16 16:05 UTC, stefanbucur commented
> @stefanbucur I updated the Bazel version to 5.0.0, which makes Bazel look for `python3` in `PATH`. The [CI run still fails](https://github.com/bazelbuild/rules_fuzzing/actions/runs/3467075874/jobs/5791585426#step:4:239), but when I run `/usr/bin/env python3` in `base-builder` locally, that passes. Not sure what's wrong here.

Interesting indeed 🤔 FWIW, the CI fuzzing test has been broken for about 3 weeks at head too: https://github.com/bazelbuild/rules_fuzzing/actions/workflows/oss_fuzz.yml

2022-12-02 08:41 UTC, fmeum commented
@stefanbucur Tests are passing now.

2022-12-02 20:15 UTC, merged